name: Build library-management-system-api 🚀

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore ./LibraryManagement.sln

      - name: Build Solution
        run: dotnet build ./LibraryManagement.sln --configuration Release --no-restore
